### ISSUE TITLE
Long startup time and main thread block

### ISSUE THREAD

**Issue by xezero** [shakebugs/shake-ios#7] opened 2020-11-13 00:52 UTC
Calling Shake.start() takes a while to complete and blocks the main thread (calling it on a background thread triggers the Main Thread Checker for accessing various UIKit calls).

Is there any way we can delay the initialization of any UIKit classes on starting Shake?

**Comment by david-decode** [comment] 2020-11-13 09:11
Hi xezero,

Thanks for the report.

The fix for the issue where Shake blocks the main thread is already implemented and passed QA. So expect this one fixed in the next release which should be anytime soon.

As for the one with the Main Thread checker warnings, the issue is moved to the top of the backlog so we will be fixing this one soon enough. This fix won't be included in the upcoming release due to internal priority reasons, but I expect it to be included in one of the subsequent releases.

Again, thanks for pointing this stuff out.

Cheers,

David
Shake Team

**Closed** 2021-01-04 09:01 UTC
